linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.15"
    # https://staticcheck.io/docs/options#checks
    checks: ["all"]
